### ISSUE TITLE
Enhance ocp_efs to support Multi-AZ

### ISSUE THREAD

**Issue by svelagap** [ibm-mas/ansible-devops#827] opened 2023-05-20 02:37 UTC
Currently the role ocp_efs creates EFS in a single zone. It would be convenient if the role can detect if a VPC is Multi-AZ and create EFS in Multi-AZ.

It would also be good to have the option to pick a Provisioned EFS.

For now I have to provision EFS manually for Multi-AZ

**Comment by maulik-modi22** [comment] 2023-05-23 09:55
#651

**Comment by JonahLuckett** [comment] 2024-08-28 16:03
Closing as duplicate of https://github.com/ibm-mas/ansible-devops/issues/651

**Closed by JonahLuckett** 2024-08-28 16:03 UTC
Labels: ROSA, Improvement/Tweak, EFS
