### ISSUE TITLE
MAS installation fails on ibm.mas_devops.mongodb : Load CASE bundle versions

### ISSUE THREAD

**Issue by alicenahas** [ibm-mas/ansible-devops#1001] opened 2023-09-07 12:39 UTC
This is a very similar error to #992.

However, once it's a different file `v8-manage-amd64.yml` , I was not sure if it could be fixed on the same issue. While running oneclick_core playbook, MAS installation fails on mongodb. Here is the error:

`TASK [ibm.mas_devops.mongodb : Load CASE bundle versions] **********************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access '/root/.ansible/collections/ansible_collections/ibm/mas_devops/roles/mongodb/../../common_vars/casebundles/v8-manage-amd64.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}`

Log is attached [here](https://github.com/ibm-mas/ansible-devops/files/12549015/log.txt)

**Comment by andrercm** [comment] 2023-09-11 18:57
Duplicate of https://github.com/ibm-mas/ansible-devops/issues/992

**Closed by andrercm** 2023-09-11 18:57 UTC
