### ISSUE TITLE
Grafana role replaces entire cluster-monitoring-config CM instead of patching

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#1499] opened 2024-10-03 06:31 UTC
### Collection version

22.5.2

### Environment information

```console
quay.io/ibmmas/cli:10.9.2
```

### What happened?

When install_core playbook is run, by default it also installs grafana. Grafana role changes the CM named cluster-monitoring-config to include enableUserWorkload: true parameter. However, the CM is not patched, but replaced. If there was any previous configuration in the CM it is lost. Corresponding code: file ibm/mas_devops/roles/grafana/tasks/install/main.yml lines 9-23.
Expected behaviour: grafana role should append enableUserWorkload: true to current configuration stored in ConfigMap if that parameter is not set.

### Relevant log output

```shell
n/a
```

**Comment by durera** [comment] 2024-11-01 23:35
Duplicate of https://github.com/ibm-mas/ansible-devops/issues/1458 (which I'm chasing the dev team to fix next sprint)

**Closed by durera** 2024-11-01 23:35 UTC
Labels: Bug Report, Duplicate
